### ISSUE TITLE
运行插件报错了

### ISSUE THREAD

**Issue by zhcxk1998** [realywithoutname/mini-program-webpack-loader#43]
```
TypeError: Cannot read property 'updateHash' of undefined
    at getContentHash (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\helpers\calc-content-hash.js:18:10)
    at MiniProgramPlugin.hasChange (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\plugin\MiniProgramPlugin.js:200:25)
    at Object.keys.forEach.file (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\plugin\MiniProgramPlugin.js:228:30)
    at Array.forEach (<anonymous>)
    at MiniProgramPlugin.setEmitHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\plugin\MiniProgramPlugin.js:225:25)
    at _next1 (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at _err1 (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:39:1)
    at FileEntryPlugin.setEmitHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\plugin\FileEntryPlugin.js:173:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:35:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compiler.js:491:19)
    at onCompiled (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compiler.js:278:9)
    at hooks.afterCompile.callAsync.err (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compilation.js:1414:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\webpack\lib\Compilation.js:1409:36)
    at _err0 (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at MiniProgramPlugin.additionalAssets (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\plugin\MiniProgramPlugin.js:391:5)
    at compilation.hooks.additionalAssets.tapAsync.callback (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\mini-program-webpack-loader\src\plugin\MiniProgramPlugin.js:153:87)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\46420\Desktop\TX-Project\sell-healper\node_modules\tapable\lib\Hook.js:154:20)
```

**Comment by realywithoutname** [comment]
可以调试下具体是什么文件导致的。比如隐藏文件，ext.json 等。
